CREATE TABLE [dbo].[LOAIPHONG]
(
	[MALOAIPHONG] NCHAR(10) NOT NULL PRIMARY KEY, 
    [TENLOAIPHONG] NVARCHAR(50) NULL, 
    [GIA] MONEY NULL
)
CREATE TABLE [dbo].[NHANVIEN]
(
	[MANV] NCHAR(10) NOT NULL PRIMARY KEY, 
    [TENNV] NVARCHAR(50) NULL, 
    [NGAYSINH] DATETIME NULL, 
    [GIOITINH] NCHAR(10) NULL, 
    [SDTNV] INT NULL, 
    [DIACHINV] NVARCHAR(50) NULL
)
CREATE TABLE [dbo].[PHIEUTHUE]
(
	[MATHUE] INT NOT NULL PRIMARY KEY, 
    [NGAYTHUE] DATETIME NULL,
	[MANV] NCHAR(10) NULL,
	[MAKH] NCHAR(10) NULL
)
CREATE TABLE [dbo].[KHACHHANG]
(
	[MAKH] INT NOT NULL PRIMARY KEY, 
    [TENKH] NVARCHAR(50) NULL, 
    [DIACHIKH] NVARCHAR(50) NULL,
	[SOCMND] INT NULL,
	[SDTKH] NVARCHAR(50) NULL
)
CREATE TABLE [dbo].[HOADON]
(
	[MAHD] INT NOT NULL PRIMARY KEY, 
    [TENHD] NVARCHAR(50) NULL, 
    [TONGTIENDV] MONEY NULL, 
    [NGAYTHANHTOAN] DATETIME NULL, 
    [MANV] NCHAR(10) NULL
)
CREATE TABLE [dbo].[CTPHONG]
(
	[NGAYDI] INT NOT NULL PRIMARY KEY, 
    [MATHUE] NCHAR(10) NULL, 
    [MAPHONG] NCHAR(10) NULL, 
)
CREATE TABLE [dbo].[PHONG]
(
	[MAPHONG] NCHAR(10) NOT NULL PRIMARY KEY, 
    [TENPHONG] NVARCHAR(50) NULL, 
    [TINHTRANG] NVARCHAR(50) NULL, 
    [MALOAIPHONG] NCHAR(10) NULL
)
CREATE TABLE [dbo].[LOAIPHONG]
(
	[MALOAIPHONG] NCHAR(10) NOT NULL PRIMARY KEY, 
    [TENLOAIPHONG] NVARCHAR(50) NULL,
	[GIA] MONEY NULL,
)
CREATE TABLE [dbo].[PHIEUSDDV]
(
	[MAPHIEU] NCHAR(10) NOT NULL PRIMARY KEY, 
    [NGAYSUDUNG] DATETIME NULL, 
    [MATHUE] NCHAR(10) NULL, 
)
CREATE TABLE [dbo].[DICHVU]
(
	[MADV] NCHAR(10) NOT NULL PRIMARY KEY, 
    [TENDV] NVARCHAR(50) NULL, 
    [DONGIAHIENTAI] MONEY NULL
)
CREATE TABLE [dbo].[CTPHIEUSDDV]
(
	[SOLUONG] INT NOT NULL PRIMARY KEY, 
    [DONGIA] MONEY NULL, 
    [MAPHIEU] NCHAR(10) NULL, 
    [MADV] NCHAR(10) NULL
)

